
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.service=postgres"
      - "traefik.tcp.services.postgres.loadBalancer.server.port=5432"

  app-service:
    build: ./backend
    command: uv run python main/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.http.routers.app-service.rule=Host(`localhost`)"

  pgadmin:
    image: dpage/pgadmin4:9.8
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    labels:
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"

  frontend:
    build: ./frontend
    command: npx expo start --lan
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "8081:8081"
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: ${REACT_NATIVE_PACKAGER_HOSTNAME}
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
  
  load-balancer:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.postgres.address=:5432/tcp"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "8080:8080"
      - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: